name: URL check

on:
  schedule:
    - cron:  '0 0 * * 1'  # once a week at 0:00 UTC
  workflow_dispatch:

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check URLs
        run: |
          docker pull ghcr.io/mobilefirstllc/checker:latest
          docker run --rm -i \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            ghcr.io/mobilefirstllc/checker:latest < README.md
          
